<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eirik Eriksen Heen &amp; ChatGPT">
<meta name="dcterms.date" content="2024-09-11">

<title>Forelesning 4: Sampling og punktestimater</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="SOK2009_2024_F4_Simulering_files/libs/clipboard/clipboard.min.js"></script>
<script src="SOK2009_2024_F4_Simulering_files/libs/quarto-html/quarto.js"></script>
<script src="SOK2009_2024_F4_Simulering_files/libs/quarto-html/popper.min.js"></script>
<script src="SOK2009_2024_F4_Simulering_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SOK2009_2024_F4_Simulering_files/libs/quarto-html/anchor.min.js"></script>
<link href="SOK2009_2024_F4_Simulering_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SOK2009_2024_F4_Simulering_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SOK2009_2024_F4_Simulering_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SOK2009_2024_F4_Simulering_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SOK2009_2024_F4_Simulering_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Forelesning 4: Sampling og punktestimater</h1>
<p class="subtitle lead">Sok-2009 h24</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eirik Eriksen Heen &amp; ChatGPT </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 11, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="sampling-og-punktestimater" class="level1">
<h1>Sampling og Punktestimater</h1>
<section id="introduksjon" class="level3">
<h3 class="anchored" data-anchor-id="introduksjon">Introduksjon</h3>
<p>I dette kapittelet skal vi utforske et av de mest fundamentale konseptene innen statistikk: <strong>sampling</strong> (eller utvalg, på norsk). Sampling er en teknikk som lar oss trekke konklusjoner om en hel populasjon ved å analysere en mindre delmengde av dataene. Men hvorfor er dette viktig? La oss begynne med et praktisk eksempel.</p>
</section>
<section id="motivasjon-estimering-av-frankrikes-befolkning" class="level3">
<h3 class="anchored" data-anchor-id="motivasjon-estimering-av-frankrikes-befolkning">Motivasjon: Estimering av Frankrikes Befolkning</h3>
<p>Forestill deg at vi vil finne ut hvor mange mennesker som bor i Frankrike. Den tradisjonelle metoden ville være å gjennomføre en folketelling, hvor man kontakter hver eneste husholdning for å få nøyaktige tall. Dette er imidlertid en svært kostbar og tidkrevende prosess, spesielt i et land med millioner av innbyggere. Derfor gjennomfører de fleste land folketellinger bare hvert femte eller tiende år.</p>
</section>
<section id="en-historisk-løsning-sampling" class="level3">
<h3 class="anchored" data-anchor-id="en-historisk-løsning-sampling">En Historisk Løsning: Sampling</h3>
<p>I 1786 oppdaget den franske matematikeren Pierre-Simon Laplace at det var mulig å estimere befolkningen på en langt mer effektiv måte. I stedet for å spørre alle husholdninger, valgte han å spørre et lite utvalg husholdninger og brukte statistikk til å anslå antall personer i hele befolkningen. Denne metoden, som innebærer å arbeide med en delmengde av hele populasjonen, kalles sampling.</p>
</section>
<section id="populasjon-vs.-utvalg" class="level3">
<h3 class="anchored" data-anchor-id="populasjon-vs.-utvalg">Populasjon vs.&nbsp;Utvalg</h3>
<p>For å forstå sampling fullt ut, er det viktig å skille mellom to begreper: populasjon og utvalg. <strong>Populasjonen</strong> er den komplette mengden av data du er interessert i. I eksemplet vårt er dette den totale befolkningen i Frankrike, men i statistikk kan populasjon referere til alle mulige typer data, ikke bare mennesker. Utfordringen er ofte at vi ikke har tilgang til data for hele populasjonen, og vi må derfor arbeide med et <strong>utvalg</strong>, som er en mindre delmengde av dataene.</p>
</section>
<section id="hvorfor-bruker-vi-sampling" class="level3">
<h3 class="anchored" data-anchor-id="hvorfor-bruker-vi-sampling">Hvorfor Bruker vi Sampling?</h3>
<p>Sampling er ikke bare en praktisk tilnærming – det er en nødvendighet i mange situasjoner. Her er noen grunner til at sampling er så viktig:</p>
<ol type="1">
<li><p><strong>Ressursbesparende</strong>: Det er ofte tids- og kostnadskrevende å samle inn data fra en hel populasjon. Ved å bruke sampling kan vi oppnå betydelige besparelser av tid, penger og arbeidskraft.</p></li>
<li><p><strong>Håndterbarhet</strong>: Store datamengder kan være vanskelig å analysere. Et representativt utvalg gir oss en mindre, mer håndterlig datamengde som er lettere å arbeide med uten å miste essensiell informasjon.</p></li>
<li><p><strong>Raskere resultater</strong>: I situasjoner der beslutninger må tas raskt, gjør sampling det mulig å utføre analyser og trekke konklusjoner på kort tid.</p></li>
<li><p><strong>Nøyaktighet og generaliserbarhet</strong>: Med riktig designet sampling kan vi trekke pålitelige konklusjoner om populasjonen basert på utvalget. Gjennom statistiske teknikker kan vi også estimere usikkerheten knyttet til disse konklusjonene.</p></li>
<li><p><strong>Begrensninger ved total undersøkelse</strong>: I noen tilfeller er det umulig å undersøke hele populasjonen. For eksempel, når vi tester holdbarheten til produkter, kan vi ikke teste alle produktene, da dette ville innebære å ødelegge dem.</p></li>
</ol>
</section>
<section id="typer-av-samplingmetoder" class="level3">
<h3 class="anchored" data-anchor-id="typer-av-samplingmetoder">Typer av Samplingmetoder</h3>
<p>Det finnes flere metoder for å trekke ut et representativt utvalg fra en populasjon. De vanligste metodene inkluderer:</p>
<ol type="1">
<li><p><strong>Enkel tilfeldig sampling</strong>:</p>
<ul>
<li>Hver enhet i populasjonen har like stor sjanse til å bli valgt. Dette er den mest grunnleggende formen for sampling og brukes ofte som et grunnlag for mer komplekse metoder.</li>
</ul></li>
<li><p><strong>Systematisk sampling</strong>:</p>
<ul>
<li>Hver n-te enhet fra en ordnet populasjon blir valgt. For eksempel kan vi velge hver 10. kunde fra en kundeliste for undersøkelsen.</li>
</ul></li>
<li><p><strong>Stratifisert sampling</strong>:</p>
<ul>
<li>Populasjonen deles inn i homogene undergrupper eller “strata” basert på en viss egenskap (som alder, kjønn, inntekt), og et tilfeldig utvalg trekkes fra hver stratum. Dette sikrer at alle undergrupper er representert i utvalget.</li>
</ul></li>
<li><p><strong>Klynge sampling</strong>:</p>
<ul>
<li>Populasjonen er delt inn i grupper eller “klynger”, og deretter velges hele klynger tilfeldig. Dette brukes ofte når populasjonen er geografisk spredt.</li>
</ul></li>
<li><p><strong>Multistadielt sampling</strong>:</p>
<ul>
<li>En kombinasjon av forskjellige samplingmetoder, der utvalget trekkes i flere stadier. For eksempel, kan man først velge klynger, og deretter utføre enkel tilfeldig sampling innen hver valgt klynge.</li>
</ul></li>
</ol>
</section>
<section id="videre-utforskning-punktestimater" class="level3">
<h3 class="anchored" data-anchor-id="videre-utforskning-punktestimater">Videre Utforskning: Punktestimater</h3>
<p>Når vi jobber med et utvalg fra populasjonen, utfører vi beregninger som gir oss <strong>punktestimater</strong> (slik som gjennomsnittet eller median) – enkle estimater som gir oss en indikasjon på hva vi kan forvente i hele populasjonen. For eksempel, dersom vi vil anslå gjennomsnittlig inntekt i en befolkning, kan vi bruke gjennomsnittsinntekten fra vårt utvalg som et punktestimat for hele populasjonen. Punktestimater er essensielle fordi de gir oss et konkret tall å arbeide med, selv om de alltid kommer med en viss usikkerhet som vi må ta hensyn til.</p>
</section>
<section id="fordeler-og-ulemper-med-sampling" class="level3">
<h3 class="anchored" data-anchor-id="fordeler-og-ulemper-med-sampling">Fordeler og Ulemper med Sampling</h3>
<p><strong>Fordeler:</strong></p>
<ul>
<li><p>Kostnadseffektivitet og tidsbesparelse.</p></li>
<li><p>Tillater undersøkelser av store populasjoner med begrensede ressurser.</p></li>
<li><p>Enkelt å administrere og analysere.</p></li>
</ul>
<p><strong>Ulemper:</strong></p>
<ul>
<li><p>Potensiell risiko for skjevhet hvis utvalget ikke er representativt for populasjonen.</p></li>
<li><p>Samplingfeil kan oppstå, som fører til unøyaktige konklusjoner.</p></li>
<li><p>Krever nøye planlegging og statistisk ekspertise for å sikre at utvalget er representativt.</p></li>
</ul>
</section>
<section id="samplingsfeil-og-bias" class="level3">
<h3 class="anchored" data-anchor-id="samplingsfeil-og-bias">Samplingsfeil og Bias</h3>
<p>Selv om sampling er en kraftig metode, er det viktig å være oppmerksom på potensielle feil og bias som kan oppstå. <strong>Samplingsfeil</strong> refererer til differansen mellom parameteren til utvalget og parameteren til populasjonen. Dette kan være et resultat av variabiliteten i utvalgene som trekkes. <strong>Bias</strong> oppstår når utvalget ikke er representativt for populasjonen, noe som kan føre til skjevheter i resultatene. Eksempler på bias inkluderer seleksjonsbias, der enkelte grupper i populasjonen har større sannsynlighet for å bli inkludert i utvalget, og responsbias, der svarene fra respondentene kan påvirkes av måten spørsmålene er stilt på.</p>
</section>
<section id="konklusjon" class="level3">
<h3 class="anchored" data-anchor-id="konklusjon">Konklusjon</h3>
<p>Sampling er et fundamentalt verktøy i statistisk analyse som muliggjør effektive og pålitelige konklusjoner om en populasjon basert på et mindre utvalg. Gjennom riktig valg av samplingmetode og nøye oppmerksomhet på potensielle feil og bias, kan vi sikre at resultatene våre er både nøyaktige og generaliserbare til den bredere populasjonen. I det neste kapittelet vil vi utforske hvordan vi kan bruke statistisk inferens til å trekke konklusjoner om populasjonen basert på data fra våre utvalg.</p>
</section>
</section>
<section id="tilfeldige-tall-og-pseudo-tilfeldige-tall" class="level1">
<h1>Tilfeldige Tall og Pseudo-Tilfeldige Tall</h1>
<section id="introduksjon-1" class="level4">
<h4 class="anchored" data-anchor-id="introduksjon-1">Introduksjon</h4>
<p>Når vi arbeider med statistiske analyser og simuleringer, spiller tilfeldige tall en sentral rolle. Enten vi trekker et tilfeldig utvalg fra en populasjon, simulerer utfall av eksperimenter, eller estimerer sannsynligheter gjennom Monte Carlo-simuleringer, er bruken av tilfeldige tall en nødvendig komponent. Men hva mener vi egentlig med “tilfeldige tall”, og hvordan genererer vi dem i et dataprogram som R?</p>
</section>
<section id="tilfeldige-tall-vs.-pseudo-tilfeldige-tall" class="level4">
<h4 class="anchored" data-anchor-id="tilfeldige-tall-vs.-pseudo-tilfeldige-tall">Tilfeldige Tall vs.&nbsp;Pseudo-Tilfeldige Tall</h4>
<p>I teorien er et tilfeldig tall et tall generert på en måte som gjør det fullstendig uforutsigbart. I praksis, når vi bruker en datamaskin, jobber vi ikke med “ekte” tilfeldige tall, men med <strong>pseudo-tilfeldige tall</strong>. Disse tallene er produsert av en algoritme, og selv om de ser tilfeldige ut, er de faktisk deterministiske – noe som betyr at de er basert på en startverdi, kalt en <strong>seed</strong>.</p>
<ul>
<li><p><strong>Tilfeldige tall</strong>: Genereres på en måte som er uforutsigbar og uten noen mønster.</p></li>
<li><p><strong>Pseudo-tilfeldige tall</strong>: Genereres av en algoritme som gir tall som ser tilfeldige ut, men som er fullt reproduserbare hvis man kjenner startverdien (seed).</p></li>
</ul>
</section>
<section id="hvorfor-bruker-vi-pseudo-tilfeldige-tall" class="level4">
<h4 class="anchored" data-anchor-id="hvorfor-bruker-vi-pseudo-tilfeldige-tall">Hvorfor Bruker vi Pseudo-Tilfeldige Tall?</h4>
<p>Det er flere grunner til at vi ofte bruker pseudo-tilfeldige tall i statistikk og programmering:</p>
<ol type="1">
<li><p><strong>Reproduserbarhet</strong>: Fordi pseudo-tilfeldige tall er deterministiske, kan vi gjenskape nøyaktig de samme “tilfeldige” sekvensene hvis vi starter med samme seed. Dette er avgjørende når vi vil at andre skal kunne reprodusere våre resultater, eller når vi ønsker å kjøre den samme analysen flere ganger for å bekrefte resultatene.</p></li>
<li><p><strong>Kontroll</strong>: I vitenskapelige eksperimenter og simuleringer kan det være nyttig å kunne kontrollere og gjenskape visse “tilfeldige” utfall, for å undersøke hvordan variasjoner påvirker resultatene.</p></li>
<li><p><strong>Effektivitet</strong>: Å bruke en algoritme for å generere pseudo-tilfeldige tall er mye raskere og enklere enn å forsøke å få tilgang til ekte tilfeldige prosesser, som fysiske fenomen eller spesialisert maskinvare.</p></li>
</ol>
</section>
<section id="hvordan-genererer-vi-pseudo-tilfeldige-tall-i-r" class="level4">
<h4 class="anchored" data-anchor-id="hvordan-genererer-vi-pseudo-tilfeldige-tall-i-r">Hvordan Genererer vi Pseudo-Tilfeldige Tall i R?</h4>
<p>R, som et statistisk programmeringsspråk, har innebygde funksjoner for å generere pseudo-tilfeldige tall. En av de viktigste funksjonene du vil møte er <code>set.seed()</code>. Denne funksjonen setter startverdien for generatoren av pseudo-tilfeldige tall, slik at du kan få konsistente resultater.</p>
<p>La oss se på et eksempel:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setter en seed</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># vi kaster en 6'er terning 10 gang</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">10</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1 5 1 1 2 4 2 2 1 4</code></pre>
</div>
</div>
<p>Hvis du kjører koden over, vil du alltid få de samme 10 tallene. Det er fordi <code>set.seed(42)</code> sikrer at den pseudo-tilfeldige tallgeneratoren starter fra samme utgangspunkt hver gang. Dette er nyttig for å sikre at dine resultater er reproduserbare.</p>
<p>La oss prøve dette på nytt, først setter vi en ny seed så setter vi seeden tilbake til 42.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setter en seed som IKKE er 42</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">13</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># vi kaster en 6'er terning 10 gang</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">10</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3 5 2 5 6 6 4 5 4 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setter seeden tilbake til 42</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># vi kaster en 6'er terning 10 gang</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">10</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1 5 1 1 2 4 2 2 1 4</code></pre>
</div>
</div>
<p>Som du ser så når vi gjøre koden på nytt får andre linje nøyaktig samme tall som første gang. Altså 1, 5, 1, osv.</p>
<p>Til slutt så trenger ikke disse tilfeldig tallene komme fra samme kode, det er kun rekkefølgen som er avgjørende.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>Vi får de samme første fem tallene.</p>
</section>
<section id="hvorfor-sette-en-seed" class="level4">
<h4 class="anchored" data-anchor-id="hvorfor-sette-en-seed">Hvorfor Sette en Seed?</h4>
<p>La oss si at du utfører en simulering for å estimere gjennomsnittet av en populasjon ved hjelp av mange tilfeldige utvalg. For å gjøre dette kjører du kanskje simuleringen flere ganger. Hvis du ikke setter en seed, vil hver kjøring gi deg forskjellige tall. Dette kan være ønskelig hvis du vil teste forskjellige scenarier, men det kan også gjøre det vanskelig å sammenligne resultater eller dele arbeidet ditt med andre.</p>
<p>Ved å sette en seed, kan du sikre at hver kjøring starter fra samme punkt, noe som gjør det enklere å sammenligne simuleringene eller få hjelp fra andre:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Eksempel på bruk av seed i en simulering vi regner ut 1 000 gjennomsnitt av å kaste 10 terninger. </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Setter en statring seed</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># replicate() gjør følgene ting x antall gang</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>sim_means <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>                       <span class="co"># Tar gjennomsnittet</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">mean</span>(</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>                         <span class="co"># ruller 10 6'er terninger </span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">10</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Lager et histogram av de 1 000 gjennomsnittene av å kaste 10 6'er ternigner </span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sim_means, <span class="at">main =</span> <span class="st">"Histogram av simulerte gjennomsnitt"</span>, <span class="at">xlab =</span> <span class="st">"Gjennomsnitt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SOK2009_2024_F4_Simulering_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I koden over har vi satt en seed med <code>set.seed(123)</code>, og deretter simulert 1000 gjennomsnitt ved hjelp av <code>replicate()</code>-funksjonen. Hvis du eller noen andre kjører denne koden på nytt, vil de få samme histogram hver gang, noe som gjør resultatene konsistente og pålitelige.</p>
</section>
<section id="oppsummering" class="level4">
<h4 class="anchored" data-anchor-id="oppsummering">Oppsummering</h4>
<p>I dette delkapittelet har vi utforsket forskjellen mellom tilfeldige og pseudo-tilfeldige tall, og sett hvordan vi kan bruke funksjonen <code>set.seed()</code> i R for å kontrollere den pseudo-tilfeldige prosessen. Å sette en seed er spesielt nyttig når vi simulerer mange utfall og ønsker reproduserbare resultater. Når du arbeider med simuleringer eller statistiske analyser, er det viktig å forstå hvordan disse mekanismene fungerer for å sikre nøyaktighet og pålitelighet i resultatene dine.</p>
</section>
</section>
<section id="tilfeldig-sampling-og-loven-om-store-tall" class="level1">
<h1>Tilfeldig Sampling og Loven om Store Tall</h1>
<section id="introduksjon-til-tilfeldig-sampling" class="level2">
<h2 class="anchored" data-anchor-id="introduksjon-til-tilfeldig-sampling">Introduksjon til Tilfeldig Sampling</h2>
<p>Tilfeldig sampling er en grunnleggende teknikk i statistikk som brukes for å sikre at et utvalg fra en populasjon er representativt. Ved å velge individer eller enheter tilfeldig, minimerer vi risikoen for bias og gjør det mulig å generalisere funnene fra utvalget til hele populasjonen. Tilfeldig er ofte best fordi vi ikke VET noe om hvordan variablene våre er fordelt.</p>
</section>
<section id="hva-er-tilfeldig-sampling" class="level2">
<h2 class="anchored" data-anchor-id="hva-er-tilfeldig-sampling">Hva er Tilfeldig Sampling?</h2>
<p>Tilfeldig sampling innebærer å velge medlemmer fra en større populasjon på en måte hvor hvert medlem har samme sannsynlighet for å bli valgt. Dette sikrer at hvert utvalg er et rettferdig representativ av hele populasjonen, noe som er kritisk for all statistisk inferens.</p>
</section>
<section id="loven-om-store-tall" class="level2">
<h2 class="anchored" data-anchor-id="loven-om-store-tall">Loven om Store Tall</h2>
<p>En av de viktigste grunnene til at vi bruker tilfeldig sampling er loven om store tall. Denne loven er en fundamental prinsipp i sannsynlighetsteori som sier at når antallet forsøk øker, vil det aritmetiske gjennomsnittet av resultatene fra de tilfeldige hendelsene konvergere til den forventede verdien. I praksis betyr dette at jo flere observasjoner vi samler, desto nærmere kommer vi den faktiske verdien vi prøver å estimere.</p>
</section>
<section id="loven-i-praksis" class="level2">
<h2 class="anchored" data-anchor-id="loven-i-praksis">Loven i Praksis</h2>
<p>For å demonstrere loven om store tall i praksis, kan vi se på å kaste en terning. Hvis vi kaster en rettferdig terning mange nok ganger, forventer vi at vi burde nærme oss et gjennomsnitt på 3.5. Vi setter en seed slik at vi får likt resultat. Vi kaster treningen 2000 gang. Så regner vi ut gjennomsnittet etter hvert kast.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Lager en datafram</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>terning <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Nummerere kasten fra 1 til 2000</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">kast =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2000</span>, </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># kaster 2000 terninger</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">terning =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">2000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>terning <span class="ot">&lt;-</span> terning <span class="sc">%&gt;%</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Summerer opp terning kastene</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">terning_sum =</span> <span class="fu">cumsum</span>(terning)) <span class="sc">%&gt;%</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># deler på antall kast for å få gjennomsnittet</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gjennomsnitt =</span> terning_sum <span class="sc">/</span> kast)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotter resultatet</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(terning, <span class="fu">aes</span>(<span class="at">x =</span> kast, <span class="at">y =</span> gjennomsnitt )) <span class="sc">+</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">yintercept =</span> <span class="fl">3.5</span>),</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span><span class="dv">1</span>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SOK2009_2024_F4_Simulering_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vi ser at gjennomsnittet tilnærmer seg det vi forventer av å kaste mange terninger.</p>
<section id="effekten-av-flere-observasjoner" class="level3">
<h3 class="anchored" data-anchor-id="effekten-av-flere-observasjoner">Effekten av Flere Observasjoner</h3>
<p>Når vi anvender tilfeldig sampling fra en populasjon for å estimere en parameter, som for eksempel gjennomsnitt, median eller proporsjon, vil tilførselen av flere observasjoner typisk resultere i et mer presist estimat. Dette er direkte knyttet til loven om store tall, som sier at estimatets nøyaktighet forbedres med størrelsen på utvalget.</p>
</section>
</section>
<section id="prøvefordeling" class="level2">
<h2 class="anchored" data-anchor-id="prøvefordeling">Prøvefordeling</h2>
<p>La oss utføre en simulering i R for å illustrere hvordan økningen i antall observasjoner påvirker estimatet av et populasjons gjennomsnitt. La oss tenke at vi skal finne ut høyden på personene i datasettet NHANES. I dette eksemplet skal vi tenke på hele datasettet som populasjonen, enkleste er å tenke på at dette datasettet inneholder alle personene i en lite amerikansk by. La oss finne det sanne gjennomsnittet som vi kan må med gjennom eksempelet. Vi finner også standardavviket.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Kaller opp datasettet NHANES</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>høyde <span class="ot">&lt;-</span> NHANES <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Henter kun høyden</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Height) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Fjerner alle NA</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Bruker summarise for å redusere alle observasjonene til en</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Runder også av slik at det kun blir to deimal tall</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(gjennomsnits_høyde <span class="ot">=</span> </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>              <span class="co"># Runder av nummert slik at det blir kun to desimaltall</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>              <span class="fu">round</span>(</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>                <span class="co"># Reggner ut gjennomsnittet, men fjerner alle NA's</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>                <span class="fu">mean</span>(Height,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>                ,<span class="dv">3</span>),</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>            <span class="co"># finner standaravvik</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>            sd_høyde <span class="ot">=</span> <span class="fu">sd</span>(Height,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>gjennomsnits_høyde <span class="ot">&lt;-</span> høyde <span class="sc">%&gt;%</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># her har jeg lagt til pull. Denne koden gjør av vi kan trekke ut en verdi vi spørrom</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Dette er veldig praktisk hvis vi skal bruke tallet til noe senere. Da kan vi lagre den som en variabel</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(gjennomsnits_høyde)</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="co"># skrive ut gjennomsnittshøyden.</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gjennomsnits_høyde)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 161.878</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>sd_høyde <span class="ot">&lt;-</span> høyde <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># her har jeg lagt til pull. Denne koden gjør av vi kan trekke ut en verdi vi spørrom</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Dette er veldig praktisk hvis vi skal bruke tallet til noe senere. Da kan vi lagre den som en variabel</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(sd_høyde)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># skrive ut gjennomsnittshøyden.</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sd_høyde)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20.18656659</code></pre>
</div>
</div>
<p>Gjennomsnittshøyden i byen er 161.878, og standaravvik på 20.187.</p>
<section id="oppgave" class="level4">
<h4 class="anchored" data-anchor-id="oppgave">Oppgave</h4>
<p>Før vi starter å simulerer gjennomsnittshøydene. Lag et histogram og/eller density plott av høydene. Hvilken form har dette diagramet? Hvordan tror du et et plot av gjennomsnittene kommer til å se ut?</p>
<p>Vi jobber for byrådet og blir bedt om å finne ut hvor høy personene i byen er. Men det koster penger å ta målinger så vi kan ikke måle alle. Kan vi finne ut høyden hvis vi måler 10 personer? Hva med 100 eller 500 personer?</p>
<p>Når vi samler inn data, får vi som ofte bare et forsøk, og et datasett er bare en mulig innsamling. Men med simulering kan vi fåreta mange innsamlinger og sammenlikne dem. Hva kunne vi ha funnet?</p>
<p>La oss starte med å ta gjennomsnittet høyden av 10 personer. Vi gjør dette 1000 gang. Vi lager nå en prøvefordeling av de forskjellige gjennomsnittene vi KAN få gitt at vi henter kun en gang.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setter en seed</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Henter datasettet NHANES</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>NHANES <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Henter kun høyden</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Height) <span class="sc">%&gt;%</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Fjerner alle NA</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># henter ut 50 tilfeldige personer</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># regner ut gjennomsnits høyden</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_height =</span> <span class="fu">mean</span>(Height)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 x 1
  mean_height
        &lt;dbl&gt;
1        173.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gjør det sammen men 1000 ganger, og skriver det inn i en dataframe</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>høyder10 <span class="ot">=</span> <span class="fu">data.frame</span>( simulerte_høyder <span class="ot">=</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">replicate</span>(<span class="at">n =</span> <span class="dv">1000</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="co"># Henter datasettet NHANES</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                                 NHANES <span class="sc">%&gt;%</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="co"># Henter kun høyden</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">select</span>(Height) <span class="sc">%&gt;%</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># Fjerner alle NA</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># henter ut 50 tilfeldige personer</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># regner ut gjennomsnits høyden</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">summarise</span>(<span class="at">mean_height =</span> <span class="fu">mean</span>(Height)) <span class="sc">%&gt;%</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># henter ut kun høyden </span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">pull</span>(mean_height)</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>                                 )</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotter nå gjennomsnittene av disse 10 personene</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(høyder10, <span class="fu">aes</span>(<span class="at">x=</span>simulerte_høyder))<span class="sc">+</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">135</span>,<span class="dv">180</span>)) <span class="sc">+</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> gjennomsnits_høyde, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Gjennomsnits høyder"</span>) <span class="sc">+</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Gjennonsnitts høyder av 10 personer. Gjennomført 1000 ganger"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SOK2009_2024_F4_Simulering_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regner ut gjennomsnitt og standaraviik</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>høyder10 <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">mean</span>(simulerte_høyder),<span class="fu">sd</span>(simulerte_høyder))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mean(simulerte_høyder) sd(simulerte_høyder)
1              161.95592          6.484901117</code></pre>
</div>
</div>
<p>Vi ser at gjennomsnittene vi kunne ha fått er fordelt om det sanne gjennomsnittet i rødt. Men vi kan bomme med ganske mye å finne at gjennomsnittet er 20-30 cm for mye eller lite. Vi ser at gjennomsittet er veldig nært det sanne gjennomsnittet, men standardavviket har gått fra 20.187.til 6.485. VI skal komme tilbake til endringen i standardaviiket</p>
<p>Hva skjer om vi nå får ta gjennomsnittet av 100 personer isteden for 50.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Samler inn gjennomsnittet av 100 personer 1000 ganger, og skriver det inn i en dataframe</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>høyder100 <span class="ot">=</span> <span class="fu">data.frame</span>( simulerte_høyder <span class="ot">=</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">replicate</span>(<span class="at">n =</span> <span class="dv">1000</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="co"># Henter datasettet NHANES</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                                 NHANES <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="co"># Henter kun høyden</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">select</span>(Height) <span class="sc">%&gt;%</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># Fjerner alle NA</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># henter ut 50 tilfeldige personer</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># regner ut gjennomsnits høyden</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">summarise</span>(<span class="at">mean_height =</span> <span class="fu">mean</span>(Height)) <span class="sc">%&gt;%</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># henter ut kun høyden </span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">pull</span>(mean_height)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>                                 )</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotter nå gjennomsnittene av disse 50 personene</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(høyder100, <span class="fu">aes</span>(<span class="at">x=</span>simulerte_høyder))<span class="sc">+</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">135</span>,<span class="dv">180</span>)) <span class="sc">+</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> gjennomsnits_høyde, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Gjennomsnits høyder"</span>) <span class="sc">+</span></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Gjennonsnitts høyder av 100 personer. Gjennomført 1000 ganger"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SOK2009_2024_F4_Simulering_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regner ut gjennomsnitt og standaraviik</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>høyder100 <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">mean</span>(simulerte_høyder),<span class="fu">sd</span>(simulerte_høyder))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mean(simulerte_høyder) sd(simulerte_høyder)
1             161.936556          1.945442789</code></pre>
</div>
</div>
<p>Når vi samler inn flere observasjoner per sample ser vi at vi får en mer nøyaktig målig enn tidligere. Store talls lov gjør at når vi samler i mer og mer data, kommer vi nærmere det sanne gjennomsnittet. Gjennomsnittet er som forventet 161.9 mens standardavviket til fordelingen er 1.945.</p>
<p>La oss nå gjør dette for 500 personer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Samler inn gjennomsnittet av 500 personer 1000 ganger, og skriver det inn i en dataframe</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>høyder500 <span class="ot">=</span> <span class="fu">data.frame</span>( simulerte_høyder <span class="ot">=</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">replicate</span>(<span class="at">n =</span> <span class="dv">1000</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="co"># Henter datasettet NHANES</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                                 NHANES <span class="sc">%&gt;%</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="co"># Henter kun høyden</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">select</span>(Height) <span class="sc">%&gt;%</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># Fjerner alle NA</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># henter ut 50 tilfeldige personer</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">500</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># regner ut gjennomsnits høyden</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">summarise</span>(<span class="at">mean_height =</span> <span class="fu">mean</span>(Height)) <span class="sc">%&gt;%</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># henter ut kun høyden </span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">pull</span>(mean_height)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>                                 )</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotter nå gjennomsnittene av disse 50 personene</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(høyder500, <span class="fu">aes</span>(<span class="at">x=</span>simulerte_høyder))<span class="sc">+</span></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">135</span>,<span class="dv">180</span>)) <span class="sc">+</span></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> gjennomsnits_høyde, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Gjennomsnits høyder"</span>) <span class="sc">+</span></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Gjennonsnitts høyder av 500 personer. Gjennomført 1000 ganger"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SOK2009_2024_F4_Simulering_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regner ut gjennomsnitt og standaraviik</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>høyder500 <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">mean</span>(simulerte_høyder),<span class="fu">sd</span>(simulerte_høyder))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mean(simulerte_høyder) sd(simulerte_høyder)
1            161.8861174         0.8516159906</code></pre>
</div>
</div>
<p>Når vi har 500 personer vi tar gjennomsnittet av ser vi at vi har enda mindre spredning. Det er viktig å huske at en hver av disse 1000 utfallene er like sannsynlig at vi trekker, men sjansene for at vi trekker noen nært det sanne gjennomsnittet er veldig høyt. Nå er standaravviket bare 0.852.</p>
</section>
</section>
<section id="standardfeil" class="level2">
<h2 class="anchored" data-anchor-id="standardfeil">Standardfeil</h2>
<p>Hvis vi sammenlikner datasttet og simuleringene kan vi se noe sammenheng?</p>
<p>Vi ser at gjennomsnittet er veldig nært uavhengig av antallet vi sampler. Dermed når vi har et tilfeldig utvalg antar vi at gjennomsnittet er forventingsrett, men større utvalg fører til mindre standarvvik til utvalget. Standarvviket til utvalget kalles også standardfeil.</p>
<p>Standardfeilen til en fordeling er:</p>
<p><span class="math display">\[
\text{standard feil}=\frac{standardevation(x)}{\sqrt{n}}
\]</span></p>
<p>Dette bruker vi når vi er interesert i hvor “korrekt” vi tror målingen av gjennomsnitter er. Eller hvor mye vi tror det kan bevege seg fra en siden til andre.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Antall</th>
<th>Utvalgs gjennonomsnitt</th>
<th>Utvalgs standaravvik</th>
<th>Standard feil</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Til hele populasjonen</td>
<td>161.878</td>
<td>20.187 (standaravvik)</td>
<td>0</td>
</tr>
<tr class="even">
<td>10</td>
<td>161.956</td>
<td>6.485</td>
<td>20.187/sqrt(10)=6.384</td>
</tr>
<tr class="odd">
<td>100</td>
<td>161.937</td>
<td>1.945</td>
<td>20.187/sqrt(100)=2.019</td>
</tr>
<tr class="even">
<td>500</td>
<td>161.886</td>
<td>0.852</td>
<td>20.187/sqrt(500)=0.903</td>
</tr>
</tbody>
</table>
<p>Vi kan se at standardfeilen og standaravviket til utvalget ikke er nøyakti det sammen. Dette er fordi vi har simulert datasettene og ikke får et nøyaktig tall.</p>
</section>
<section id="sentralgrenseteoremet" class="level2">
<h2 class="anchored" data-anchor-id="sentralgrenseteoremet">Sentralgrenseteoremet</h2>
<p>I eksempelet over kan vi se at når utvalgene blir større og større så blir mer og mer formet som en normal fordeling. Denne ser ut som en klokke formet fordeling, som under.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a sequence of 100 equally spaced numbers between -4 and 4</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co">#create a vector of values that shows the height of the probability distribution</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co">#for each value in x</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co">#plot x and y as a scatterplot with connected lines (type = "l") and add</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co">#an x-axis with custom labels</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">axes =</span> <span class="cn">FALSE</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="sc">-</span><span class="dv">3</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"-3s"</span>, <span class="st">"-2s"</span>, <span class="st">"-1s"</span>, <span class="st">"mean"</span>, <span class="st">"1s"</span>, <span class="st">"2s"</span>, <span class="st">"3s"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SOK2009_2024_F4_Simulering_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="definisjon-av-sentralgrenseteoremet" class="level3">
<h3 class="anchored" data-anchor-id="definisjon-av-sentralgrenseteoremet">Definisjon av Sentralgrenseteoremet</h3>
<p>Sentralgrenseteoremet sier at når et tilstrekkelig stort antall uavhengige og identisk distribuerte tilfeldige variabler blir summert, vil deres normaliserte sum konvergere mot en normalfordeling, uavhengig av den opprinnelige fordelingen til de individuelle variablene. Dette betyr at for en stor nok utvalgsstørrelse vil utvalgsmiddelet til nesten enhver fordeling være omtrent normalfordelt.</p>
<section id="viktigheten-av-clt" class="level4">
<h4 class="anchored" data-anchor-id="viktigheten-av-clt">Viktigheten av CLT</h4>
<p>Hvorfor er dette teoremet så viktig? For det første muliggjør CLT bruk av normalfordelingsmetoder for statistisk inferens — inkludert konfidensintervaller og hypotesetester — selv når populasjonen ikke er normalfordelt, så lenge utvalgsstørrelsen er stor nok. Dette er svært nyttig i praksis siden mange reelle datasett ikke følger en normalfordeling.</p>
</section>
</section>
</section>
<section id="oppsummering-betydningen-av-prøvefordelingen" class="level2">
<h2 class="anchored" data-anchor-id="oppsummering-betydningen-av-prøvefordelingen">Oppsummering: Betydningen av Prøvefordelingen</h2>
<section id="prøvefordelingens-rolle" class="level4">
<h4 class="anchored" data-anchor-id="prøvefordelingens-rolle">Prøvefordelingens Rolle</h4>
<p>I løpet av dette kapittelet har vi utforsket hvordan prøvefordelingen, eller sampling distribution, fungerer som et grunnleggende konsept i statistikken for å forstå effektene av tilfeldig sampling. Prøvefordelingen av et estimat, som et utvalgsmiddel, gir oss en visuell og kvantitativ måte å analysere variabiliteten av estimatet på når vi gjentar eksperimentet under identiske forhold.</p>
</section>
<section id="betydningen-av-flere-observasjoner" class="level4">
<h4 class="anchored" data-anchor-id="betydningen-av-flere-observasjoner">Betydningen av Flere Observasjoner</h4>
<p>Som vi har sett, bekrefter loven om store tall og sentralgrenseteoremet at jo flere tilfeldige observasjoner vi trekker fra populasjonen, desto nærmere vil vårt utvalgsmiddel ligge til populasjonens faktiske middel. Dette øker nøyaktigheten og påliteligheten av våre statistiske estimater og tester, ettersom standardfeilen i utvalgsmiddelet avtar når utvalgsstørrelsen øker.</p>
</section>
<section id="vurdering-av-usikkerhet" class="level4">
<h4 class="anchored" data-anchor-id="vurdering-av-usikkerhet">Vurdering av Usikkerhet</h4>
<p>Det er imidlertid viktig å anerkjenne at selv med store utvalg og nøye design, inneholder all statistisk inferens en grad av usikkerhet. Sjansen for å tilfeldigvis trekke et utvalg som ikke er representativt for populasjonen reduseres med større utvalg, men risikoen er aldri helt eliminert. Dette understreker viktigheten av å bruke passende statistiske metoder for å vurdere og rapportere usikkerheten i våre estimater.</p>
</section>
<section id="praktiske-implikasjoner" class="level4">
<h4 class="anchored" data-anchor-id="praktiske-implikasjoner">Praktiske Implikasjoner</h4>
<p>For praktiserende statistikere og forskere er forståelsen av prøvefordelingen avgjørende for å:</p>
<ul>
<li><p>Designe eksperimenter og studier som effektivt balanserer ressurser og ønsket nøyaktighet.</p></li>
<li><p>Beregne og tolke konfidensintervaller som gir innsikt i hvor nøyaktige våre estimater er.</p></li>
<li><p>Utføre hypotesetester med en klar forståelse av type I og type II feil, som begge er kritisk avhengig av prøvefordelingens form og spredning.</p></li>
</ul>
</section>
<section id="konklusjon-1" class="level4">
<h4 class="anchored" data-anchor-id="konklusjon-1">Konklusjon</h4>
<p>Til slutt tilbyr prøvefordelingen en kraftig ramme for statistisk resonnement. Den hjelper oss ikke bare med å forstå hva våre data sier om verden, men også hvor sikre vi kan være på disse konklusjonene. Ved å utnytte kunnskapen om prøvefordelingen kan vi ta velinformerte beslutninger som er støttet av solid matematisk teori og praktisk anvendelse.</p>
</section>
<section id="oppgaver" class="level4">
<h4 class="anchored" data-anchor-id="oppgaver">Oppgaver</h4>
<p>I datasettet <em>house_prices</em> fra pakken <em>moderndive</em> har vi dataen på mange hus og deres priser. Bruk dette datasettet igjennom disse oppgavene.</p>
<section id="oppgave-1" class="level5">
<h5 class="anchored" data-anchor-id="oppgave-1">Oppgave 1</h5>
<p>Få oversikt over hvilken variabler som finnes i datasettet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(house_prices)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Hvilken type variagler er <em>price</em>, <em>bedrooms</em>, <em>waterfront</em>, <em>zipcode</em>?</p>
</section>
<section id="oppgave-2" class="level5">
<h5 class="anchored" data-anchor-id="oppgave-2">Oppgave 2</h5>
<p>Plott fordeling av hus som har og ikke har tilgang til havet. Datasettet har 21 613 observasjoner. Hvordan blir fordeling av prøvefordelingen til tilgang til havet, hvis vi kan samle inn data på kun 300 hus? Repliker dette 2000 ganger å plott i et histogram.</p>
<p>Hvordan ser denne fordelingen ut?</p>
</section>
<section id="oppgave-3" class="level5">
<h5 class="anchored" data-anchor-id="oppgave-3">oppgave 3</h5>
<p>I datasettet, finn gjennomsnitts pris på husen og standardfeilen.</p>
</section>
</section>
</section>
</section>
<section id="bootstraping" class="level1">
<h1>Bootstraping</h1>
<p>I tidligere deler av dette kapittelet har vi fokusert på å trekke små utvalg fra en stor populasjon uten tilbakelegging, noe som betyr at hver observasjon kun blir valgt én gang. Vi har også operert under antagelsen om at vi kjenner hele populasjonen. Imidlertid er dette sjelden tilfellet i praktisk statistisk analyse. Vi har utforsket hvordan man kan lage fordelinger ved å trekke gjentatte ganger fra en kjent populasjon, men hva om vi bare har et enkelt utvalg og ingen direkte kunnskap om den underliggende populasjonen? Her kommer bootstrapping inn som en kraftfull teknikk.</p>
<section id="definisjon-av-bootstrapping" class="level4">
<h4 class="anchored" data-anchor-id="definisjon-av-bootstrapping">Definisjon av Bootstrapping</h4>
<p>Bootstrapping er en resampling-teknikk som brukes til å estimere egenskaper ved en estimator (som varians og bias) ved å anvende stor grad av sampling fra et enkelt datatasett, med tilbakelegging. Dette står i kontrast til tradisjonell sampling og kan beskrives som nesten det motsatte:</p>
<ul>
<li><p><strong>Sampling</strong>: Prosessen hvor man går fra populasjon til et utvalg.</p></li>
<li><p><strong>Bootstrapping</strong>: Prosessen hvor man bygger en teoretisk populasjon fra et utvalg for å generere mange simulerte prøver.</p></li>
</ul>
</section>
<section id="hvordan-fungerer-bootstrapping" class="level4">
<h4 class="anchored" data-anchor-id="hvordan-fungerer-bootstrapping">Hvordan Fungerer Bootstrapping?</h4>
<p>Når vi bootstrapper, tar vi gjentatte utvalg med tilbakelegging fra det opprinnelige datasettet. Dette betyr at hver gang vi velger en observasjon, legger vi den tilbake før neste trekning. På denne måten kan samme observasjon velges flere ganger i ett resample. Denne metoden lar oss:</p>
<ol type="1">
<li><p><strong>Estimere Standardfeil og Konfidensintervaller</strong>: Ved å skape mange bootstrap-prøver og beregne ønsket statistikk (for eksempel gjennomsnitt eller median) for hver prøve, kan vi skape en empirisk fordeling av estimatoren. Dette gir oss innsikt i variabiliteten og tillater oss å beregne ting som standardfeil og konfidensintervaller.</p></li>
<li><p><strong>Vurdere Robustheten av Statistiske Estimater</strong>: Ved å se hvordan estimatene varierer fra prøve til prøve, kan vi få en bedre forståelse av hvor robuste våre estimater er til tilfeldige variasjoner i dataene.</p></li>
</ol>
</section>
<section id="bootstrapper-et-gjennomsnitt" class="level3">
<h3 class="anchored" data-anchor-id="bootstrapper-et-gjennomsnitt">Bootstrapper et gjennomsnitt</h3>
<p>Hvis vi nå har samlet inn 200 forskjellige personer, hvor nært er vi det sanne gjennomsnittet?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">200</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>høyder200 <span class="ot">=</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  NHANES <span class="sc">%&gt;%</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Henter kun høyden</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Height) <span class="sc">%&gt;%</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Fjerner alle NA</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># henter ut 200 tilfeldige personer</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">200</span>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>høyder200 <span class="sc">%&gt;%</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">mean</span>(Height))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 x 1
  `mean(Height)`
           &lt;dbl&gt;
1           164.</code></pre>
</div>
</div>
<p>Som vi ser så bommet vi litt? Men hvis vi nå skulle bootstrappe denne fordelinge, er den sanne høyden nært nok? La oss tegne opp fordeling og begrense hvor 95% av fordelingen ligger. Altså sier at innfor for den vannelige variasjonen til fordelingen så mener vi at gjennomsnittet ligger mellom to punker.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">200</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>data_høyde <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( gjennomsnits_høyde <span class="ot">=</span> <span class="fu">replicate</span>(<span class="at">n=</span><span class="dv">5000</span>,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                                 høyder200 <span class="sc">%&gt;%</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># heter hele datastettet med tilbakeleg </span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">slice_sample</span>(<span class="at">prop=</span><span class="dv">1</span>, <span class="at">replace =</span><span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># vi regner ut gjennomsnittet av utvalget</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">summarise</span>(gjennomsnits_høyde <span class="ot">=</span><span class="fu">mean</span>(Height) )<span class="sc">%&gt;%</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="co"># trekker ut gjennomsnittet</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">pull</span>(gjennomsnits_høyde)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>                                 )</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_høyde, <span class="fu">aes</span>(<span class="at">x=</span>gjennomsnits_høyde))<span class="sc">+</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">quantile</span>(data_høyde<span class="sc">$</span>gjennomsnits_høyde,<span class="fl">0.025</span>))<span class="sc">+</span></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">quantile</span>(data_høyde<span class="sc">$</span>gjennomsnits_høyde,<span class="fl">0.975</span>))<span class="sc">+</span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">161.878</span>, <span class="at">colour =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SOK2009_2024_F4_Simulering_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Her ser vi at det sanne gjennomsnittet ligger akkurat innenfor 95% av fordelingen. Så vi hadde et litt skjervt utvalg, men ikke så veldig skjervt at gjennomsnitt ligger innenfor en trolig begrensing av denne fordelingen.</p>
<p>Hvis vi nå trekker ut den øvre å nedre grensen får vi det 95% konfidensitnervallet til gjennomsnittet. Eller hvor vi er ganske sikker på at gjennomsnittet ligger.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nedre grense</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(data_høyde<span class="sc">$</span>gjennomsnits_høyde,<span class="fl">0.025</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2.5% 
161.041425 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># øvre grense</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(data_høyde<span class="sc">$</span>gjennomsnits_høyde,<span class="fl">0.975</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      97.5% 
166.3980125 </code></pre>
</div>
</div>
<section id="konfidens-intervall-ved-brukk-av-standardfeil" class="level4">
<h4 class="anchored" data-anchor-id="konfidens-intervall-ved-brukk-av-standardfeil">Konfidens intervall ved brukk av standardfeil</h4>
<p>Dette kommer litt før vi starter med fordelinger, men 96% av en fordeling ligger mellom to standardfeil ned og to standarfeil opp.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>høyder200 <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">nedre_grense =</span> <span class="fu">mean</span>(Height)<span class="sc">-</span><span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(Height)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>()),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>            ø<span class="at">vre_grense =</span> <span class="fu">mean</span>(Height)<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(Height)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>())</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>            )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 x 2
  nedre_grense øvre_grense
         &lt;dbl&gt;       &lt;dbl&gt;
1         161.        166.</code></pre>
</div>
</div>
<p>Her ser vi at når vi trekker fra to standarfeil får vi nesten samme tallet som vi fikk av å simmulere, når vi legger til to standarfeil får igjen nesten samme tall som vi fikk ved å simulere.</p>
</section>
<section id="konklusjon-2" class="level4">
<h4 class="anchored" data-anchor-id="konklusjon-2">Konklusjon</h4>
<p>Bootstrapping tilbyr en fleksibel og kraftig tilnærming til statistisk inferens, spesielt når vi mangler tilgang til hele populasjonen eller når populasjonen er ukjent. Ved å utnytte datadrevne simuleringer kan bootstrapping gi verdifull innsikt i egenskapene til statistiske estimatorer, selv med begrenset eller ufullstendig data.</p>
<section id="oppgaver-1" class="level5">
<h5 class="anchored" data-anchor-id="oppgaver-1">Oppgaver</h5>
<p>Bruk datasettet <em>house_prices</em> og finn følgene.</p>
<p>Konfidens intervallet til hus prisene ved å Bootstrappe og via pluss/minus to standarfeil.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(house_prices)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(house_prices)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 21,613
Columns: 21
$ id            &lt;chr&gt; "7129300520", "6414100192", "5631500400", "2487200875", ~
$ date          &lt;date&gt; 2014-10-13, 2014-12-09, 2015-02-25, 2014-12-09, 2015-02~
$ price         &lt;dbl&gt; 221900, 538000, 180000, 604000, 510000, 1225000, 257500,~
$ bedrooms      &lt;int&gt; 3, 3, 2, 4, 3, 4, 3, 3, 3, 3, 3, 2, 3, 3, 5, 4, 3, 4, 2,~
$ bathrooms     &lt;dbl&gt; 1.00, 2.25, 1.00, 3.00, 2.00, 4.50, 2.25, 1.50, 1.00, 2.~
$ sqft_living   &lt;int&gt; 1180, 2570, 770, 1960, 1680, 5420, 1715, 1060, 1780, 189~
$ sqft_lot      &lt;int&gt; 5650, 7242, 10000, 5000, 8080, 101930, 6819, 9711, 7470,~
$ floors        &lt;dbl&gt; 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1~
$ waterfront    &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, ~
$ view          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0,~
$ condition     &lt;fct&gt; 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 3, 4, 4,~
$ grade         &lt;fct&gt; 7, 7, 6, 7, 8, 11, 7, 7, 7, 7, 8, 7, 7, 7, 7, 9, 7, 7, 7~
$ sqft_above    &lt;int&gt; 1180, 2170, 770, 1050, 1680, 3890, 1715, 1060, 1050, 189~
$ sqft_basement &lt;int&gt; 0, 400, 0, 910, 0, 1530, 0, 0, 730, 0, 1700, 300, 0, 0, ~
$ yr_built      &lt;int&gt; 1955, 1951, 1933, 1965, 1987, 2001, 1995, 1963, 1960, 20~
$ yr_renovated  &lt;int&gt; 0, 1991, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,~
$ zipcode       &lt;fct&gt; 98178, 98125, 98028, 98136, 98074, 98053, 98003, 98198, ~
$ lat           &lt;dbl&gt; 47.5112, 47.7210, 47.7379, 47.5208, 47.6168, 47.6561, 47~
$ long          &lt;dbl&gt; -122.257, -122.319, -122.233, -122.393, -122.045, -122.0~
$ sqft_living15 &lt;int&gt; 1340, 1690, 2720, 1360, 1800, 4760, 2238, 1650, 1780, 23~
$ sqft_lot15    &lt;int&gt; 5650, 7639, 8062, 5000, 7503, 101930, 6819, 9711, 8113, ~</code></pre>
</div>
</div>
</section>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>